version: '3.4'

services:
  knotdiary-api-users:
    image: jsnmgpnty/knotdiary-api-users
    ports:
      - "6002:80"
    build:
      context: .
      dockerfile: KnotDiary.UsersApi/Dockerfile
  knotdiary-api-auth:
    image: jsnmgpnty/knotdiary-api-auth
    ports:
      - "6003:80"
    build:
      context: .
      dockerfile: KnotDiary.AuthApi/Dockerfile
  knotdiary-api-gateway:
    image: jsnmgpnty/knotdiary-api-gateway
    ports:
      - "8001:80"
    build:
      context: .
      dockerfile: KnotDiary.ApiGateway/Dockerfile
